# -*- coding: utf-8 -*-
"""250397.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ovfXUDOCOb-cQIQroQ_45jpiQsYdATe
"""


# Bibliotecas
import numpy as np
from google.colab import files
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import PIL.Image as pimg
import PIL.ImageOps as pimgops
import scipy.ndimage as scimg
from unicamp_effects.registry import register

# Download das imagens
arvore = mpimg.imread('Arvore.jpg')
arvore = np.rot90(arvore, k=-1)

bicicleta = mpimg.imread('Bicicleta.jpg')
bicicleta = np.rot90(bicicleta, k=-1)

depth = mpimg.imread('Depth.jpg')
depth = np.rot90(depth, k=-1)

# Plotagem
fig, axs = plt.subplots(1, 3, figsize = (12, 4))
plt.tight_layout()

plt.subplot(131)
plt.imshow(arvore, cmap = 'gray')
plt.title('Arvore')

plt.subplot(132)
plt.imshow(bicicleta, cmap = 'gray')
plt.title('Bicicleta')

plt.subplot(133)
plt.imshow(depth, cmap = 'gray')
plt.title('Depth')

# Funções Gerais (usadas em outras funções)
@register(prefix="250397")
def ConversaoCinza(img):
  img_cinza = np.zeros((img.shape[0], img.shape[1]))
  img_cinza[:, :] = 0.3 * img[: , : , 0] + 0.59 * img[: , : , 1] + 0.11 * img[: , : , 2]

  return img_cinza

@register(prefix="250397")
def BlurCinza(img):
  filtro = np.ones((31, 31))
  filtro = filtro/filtro.sum()
  img_blur = scimg.convolve(img, filtro)

  return img_blur

@register(prefix="250397")
def Blur(img):
  filtro = np.ones((31, 31))
  filtro = filtro/filtro.sum()

  img_PIL = pimg.fromarray(img)
  img_red, img_green, img_blue = img_PIL.split()

  img_red = np.array(img_red)
  img_green = np.array(img_green)
  img_blue = np.array(img_blue)

  img_red = scimg.convolve(img_red, filtro)
  img_green = scimg.convolve(img_green, filtro)
  img_blue = scimg.convolve(img_blue, filtro)

  img_blur = np.stack([img_red, img_green, img_blue])
  img_blur = img_blur.transpose(1, 2, 0)

  return img_blur

@register(prefix="250397")
def DeteccaoBordas(img):
  img_cinza = ConversaoCinza(img)
  img_cinza = img_cinza.astype(float)

  img_cinza = BlurCinza(img_cinza)

  Sv = np.array([[1,0,-1],[2,0,-2],[1,0,-1]])
  Sh = np.array([[1,2,1],[0,0,0],[-1,-2,-1]])

  # Filtragem
  img_sv = scimg.convolve(img_cinza, Sv)
  img_sh = scimg.convolve(img_cinza, Sh)

  # Normalização
  img_sv = img_sv/img_sv.max()
  img_sh = img_sh/img_sh.max()
  img_sv_preto = img_sv <= 0
  img_sv[img_sv_preto == True] = 0
  img_sh_preto = img_sh <= 0
  img_sh[img_sh_preto == True] = 0

  # Mudança de preto para branco (apenas melhora para observação do efeito)
  img_sv_teste = img_sv <= 0.05
  img_sv[img_sv_teste == True] = 1.0
  img_sh_teste = img_sh <= 0.05
  img_sh[img_sh_teste == True] = 1.0

  img_sobel = ((img_sv ** 2) + (img_sh ** 2)) ** (1/2)

  # Normalização
  img_sobel = img_sobel/img_sobel.max()

  # Mudança para int
  img_cinza = img_cinza.astype(int)
  img_sv = img_sv.astype(int)
  img_sh = img_sh.astype(int)
  img_sobel = img_sobel.astype(int)

  return img_sobel

@register(prefix="250397")
def DeteccaoIntervaloCor(img, min, max):
  img_PIL = pimg.fromarray(img)
  img_red, img_green, img_blue = img_PIL.split()

  img_red = np.array(img_red)
  img_green = np.array(img_green)
  img_blue = np.array(img_blue)

  img_red_bool_min = img_red >= min[0]
  img_red_bool_max = img_red <= max[0]
  img_red_bool = img_red_bool_min & img_red_bool_max

  img_green_bool_min = img_green >= min[1]
  img_green_bool_max = img_green <= max[1]
  img_green_bool = img_green_bool_min & img_green_bool_max

  img_blue_bool_min = img_red >= min[2]
  img_blue_bool_max = img_red <= max[2]
  img_blue_bool = img_blue_bool_min & img_blue_bool_max

  img_bool = np.stack([img_red_bool, img_green_bool, img_blue_bool])
  img_bool = img_bool.transpose(1, 2, 0)

  white = np.ones((arvore.shape[0], arvore.shape[1], arvore.shape[2]), dtype = np.uint8)
  white = white * 255

  img_fim = np.where(img_bool, img, white)

  return img_fim

@register(prefix="250397")
def Pixelizacao(img):
  linhas, colunas = np.indices((img.shape[0], img.shape[1]))

  # Refere a apenas um pixel da região 5x5
  linhas_aux = (linhas//31) * 31
  colunas_aux = (colunas//31) * 31

  # Condição para substituir pixels
  img_bool = (linhas % 31 == 0) & (colunas % 31 == 0)

  # Obtém o número certo de elementos do array
  linhas_final = linhas_aux[img_bool == False]
  colunas_final = colunas_aux[img_bool == False]

  img_fim = img.copy()
  img_fim[img_bool == False] = img[linhas_final, colunas_final]

  return img_fim

"""# Efeito Arvore
O efeito árvore não foi terminado, pois houve problema que a booleana gerada por arvore intervalo deveria ser verdadeiro se qualquer dos valores fosse menor que 255 entre as 3 dimensões do RGB, mas resultaria em, na medida do possível, apenas a borda da árvore e folhas (que por serem pequenas eram praticamente tudo borda) e outros elementos com cores similares mantendo suas cores, enquanto o resto era mudado para branco.
"""

@register(prefix="250397")
def Arvore(arvore_inicial):
  # Função de detecção de borda e função de blur
  arvore_bordas = DeteccaoBordas(arvore_inicial)
  arvore_intervalo = DeteccaoIntervaloCor(arvore_inicial, (50, 50, 50), (60, 60, 60))

  arvore_aux_1 = arvore_intervalo < 255

  arvore_aux_2 = arvore_bordas <= 50
  arvore_aux_2 = np.array([arvore_aux_2, arvore_aux_2, arvore_aux_2])
  arvore_aux_2 = arvore_aux_2.transpose(1, 2, 0)

  arvore_bool = arvore_aux_1 & arvore_aux_2

  white = np.ones((arvore.shape[0], arvore.shape[1], arvore.shape[2]), dtype = np.uint8)
  white = white * 255

  arvore_fim = np.where(arvore_bool, arvore_inicial, white)

  # Plotagem
  fig, axs = plt.subplots(2, 2, figsize = (12, 4))
  plt.tight_layout()

  plt.subplot(141)
  plt.imshow(arvore_inicial)
  plt.title('Original')

  plt.subplot(142)
  plt.imshow(arvore_bordas, cmap = 'gray')
  plt.title('Bordas')

  plt.subplot(143)
  plt.imshow(arvore_intervalo)
  plt.title('Intervalo Cor')

  plt.subplot(144)
  plt.imshow(arvore_fim)
  plt.title('Final')

  return arvore_fim

arvore_fim = Arvore(arvore)

"""# Efeito Bicicleta
O efeito realiza a pixelização da imagem.
"""

@register(prefix="250397")
def Bicicleta(bicicleta_inicial):
  bicicleta_fim = Pixelizacao(bicicleta_inicial)

  # Plotagem
  fig, axs = plt.subplots(1, 2, figsize = (12, 4))
  plt.tight_layout()

  plt.subplot(121)
  plt.imshow(bicicleta_inicial)
  plt.title('Original')

  plt.subplot(122)
  plt.imshow(bicicleta_fim)
  plt.title('Final')

  return bicicleta_fim

bicicleta_fim = Bicicleta(bicicleta)

"""# Efeito Depth
O efeito realizado teve sua proposta levemente alterado para realizar o blur das bordas detectadas. Ele ocorre ao detectar bordas e realizar o blur deleas que coincidem com a maior parte do ambiente além da varanda, visto que as diversas árvores geram diversas bordas.
"""

@register(prefix="250397")
def Depth(depth_inicial):
  # Função de detecção de borda e função de blur
  depth_bordas = DeteccaoBordas(depth_inicial)
  depth_blur = Blur(depth_inicial)

  # Auxiliar para realizar blur
  depth_aux = depth_bordas <= 50
  depth_aux = np.array([depth_aux, depth_aux, depth_aux])
  depth_aux = depth_aux.transpose(1, 2, 0)

  # Aplicação do efeito
  depth_fim = np.where(depth_aux, depth_blur, depth_inicial)

  # Plotagem
  fig, axs = plt.subplots(2, 2, figsize = (12, 4))
  plt.tight_layout()

  plt.subplot(141)
  plt.imshow(depth_inicial)
  plt.title('Original')

  plt.subplot(143)
  plt.imshow(depth_bordas, cmap = 'gray')
  plt.title('Bordas')

  plt.subplot(142)
  plt.imshow(depth_blur)
  plt.title('Blur')

  plt.subplot(144)
  plt.imshow(depth_fim)
  plt.title('Final')

  return depth_fim

depth_fim = Depth(depth)

# Download das imagens finais
import cv2

cv2.imwrite('arvore_fim.jpg', arvore_fim)
cv2.imwrite('bicicleta_fim.jpg', bicicleta_fim)
cv2.imwrite('depth_fim.jpg', depth_fim)

files.download('arvore_fim.jpg')
files.download('bicicleta_fim.jpg')
files.download('depth_fim.jpg')